services:
  - type: web
    name: faceid-supervised
    env: python
    plan: free
    buildCommand: "pip install --no-deps -r requirements.lock"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
